pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases'
        }
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'Quilt'
            url = 'https://maven.quiltmc.org/repository/release'
        }
    }
    includeBuild '../'
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.9.0'
}

rootProject.name = 'modsdotgroovy-test'

buildCache {
    remote(HttpBuildCache) { HttpBuildCache cache -> cache.tap {
        url = 'https://gradlecache.groovymc.org/cache/'
    }}
}

enableFeaturePreview 'GROOVY_COMPILATION_AVOIDANCE'
enableFeaturePreview 'TYPESAFE_PROJECT_ACCESSORS'
enableFeaturePreview 'STABLE_CONFIGURATION_CACHE'

includeBuild '../'

include 'multiplatform:common'
if (forge_enabled == 'true') include 'forge', 'multiplatform:forge'
if (fabric_enabled == 'true') include 'fabric', 'multiplatform:fabric'
if (neoforge_enabled == 'true') include 'neoforge', 'multiplatform:neoforge'
if (neogradle_enabled == 'true') include 'neogradle'
if (quilt_enabled == 'true') include 'quilt', 'multiplatform:quilt'
if (spigot_enabled == 'true') include 'spigot'
