dependencies {
    implementation libs.groovy4.core
    compileOnly libs.jetbrains.annotations
    implementation projects.types
    implementation(libs.forkedtaskexecutor) {
        capabilities {
            requireFeature('runner')
        }
    }
}

publishing {
    publications.register('runner', MavenPublication) {
        from components.java

        pom {
            name = 'mods.groovy bootstrap'
            description = 'Bootstrap layer for running mods.groovy from another process'
            url = 'https://github.com/GroovyMC/ModsDotGroovy'
        }
    }
}

signing {
    sign publishing.publications.runner
}
