subprojects {
    group = 'org.groovymc.modsdotgroovy.stock-plugins'

    dependencies {
        implementation libs.groovy4.core.get()
        implementation(project(':core')) {
            // Can't use typesafe accessor here -- those don't let you configure capabilities apparently?
            capabilities {
                requireFeature('plugin-api')
            }
        }
        compileOnly libs.jetbrains.annotations.get()
    }
}
