name: Release Plugin
concurrency: ci-${{ github.ref }}
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Java
        run: |
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> "$GITHUB_ENV"
      - uses: gradle/gradle-build-action@v2
      - name: Publish - Plugin Portal
        run: ./gradlew publishPlugins
        env:
          GPP_KEY: ${{ secrets.GPP_KEY }}
          GPP_SECRET: ${{ secrets.GPP_SECRET }}
      - name: Publish - Modding Inquisition Maven
        run: ./gradlew publishPluginMavenPublicationToModdingInquisitionMavenRepoRepository publishModsdotgroovyPluginMarkerMavenPublicationToModdingInquisitionMavenRepoRepository -PinquisitionPublish
        env:
          MAVEN_USER: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_USER }}
